### PR TITLE
Add Bootloader commands, plus some small code optimizations

### PR DESCRIPTION
**Pull request by Akubi**
Added 3 Bootloader commands:
 - cmd 0x01 clear eeprom
 - cmd 0x02 set id
 - cmd 0x03 set parent id

Changed Makefile:
  - added BAUDRATE definition from makefile
  - addet quote on $(INCLUDES) directive for Windows directories with spaces (Issue #6)
  - change toolchain directory to "ATMEL Studio 7.0" for better compatibility and solve
    ld.exe problem in Arduino 1.8.0 version

Some small code optimization to free code space for Bootloader commands

Added modification proposal to STK500Bootloader.h. Possible to free 28bytes (commented)

### CODE REVIEW

**Comment by Akubi** [comment]
Hi tekka.
Thank for your very nice job. I'm impressed.
I yust push a request to implement bootloader commands.
Hope you can merge my request.
I also included a modificatin for issue #6 from bladika

**Comment by tekka007** [comment]
@Akubi Thanks for your input, I'll review your PR ASAP.

**Comment by Akubi** [comment]
Hi, could you take a look to my pool request ?

**Comment by tekka007** [comment]
@Akubi Not yet, postponed due to limited bandwidth.

**Comment by Akubi** [comment]
OK no problem.
I have 1 question to you.
In the STK500 protocol,  you implement a command "STK_READ_PAGE". At my point of view this is not required. We can remove this command in order to free some memory.
If you agree, I can modify my pull request with this modification.

**Comment by tekka007** [comment]
STK_READ_PAGE is used for verification, avrdude uses it

**Comment by Akubi** [comment]
Ok thank.
I don't notice than on my test and had no problems removing this part of code but ok.
I will look for other possible memory reduction.
I know it's very hard.

**Comment by schotime** [comment]
Would love to see these commands here. Trying to use them in the beta of myscontroller and they don't seem to be working. Guessing this is why?

**Comment by tekka007** [comment]
Correct

**Comment by tekka007** [comment]
@Akubi Amazing finding, what is the actual code size with your changes?

**Comment by Akubi** [comment]
@tekka007 

Hi Olivier, that depend on configuration. I tested for 16MHz 8MHz and 1MHz


| CLK | BAUDRATE | text | data | Size| Free bytes | Last used byte |
|     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |
| 16MHz | 576900 | 2028| 6| 2034| 14| 0x7FF1|
| 8MHz | 576900 | 2030| 6| 2036| 12| 0x7FF3|
| 1MHz | 9600 | 2018| 6| 2024| 24| 0x7FE7|

**Pull request merged**
