### PR TITLE
Add delay on SPI radio timing, plus some code optimizations

### PR DESCRIPTION
**Pull request by Akubi**
New:
Add delay on SPI radio in order to stabilize communication and improve transmission speed. This will especially impact 16MHz CPU and PA clones NRF24

•	10us after CSN_LOW
•	10us after CSN_HIGH
•	4us between CE_HIGH and CNS_LOW

Feature change:
•	Stop parent search when configured parent found

Optimizations:
•	Remove usage of “eeprom_update_block”. Replaced by loop using “eeprom_update_byte”
•	Refactoring of parent search
•	New byteAtoi conversion based on known string length

### CODE REVIEW

**Comment by tekka007** [comment]
@Akubi Wow, nice improvements.
How did you figure out about:
 •	4us between CE_HIGH and CNS_LOW?
Any reference?

**Comment by Akubi** [comment]
@tekka007 Thank, but only small improvements. The big job was your to do the bootloader. Modifying is easier than doing 

For timing information I use 2 sources. Of course MySensors library and Nordic nRF24L01+ Datasheet. For the 4us I base my decision to add it based on Datasheet (https://www.sparkfun.com/datasheets/Components/SMD/nRF24L01Pluss_Preliminary_Product_Specification_v1_0.pdf) chapter 6.1.7, Tpece2cns min. 4us (Delay from CE positive edge to CNS low).
For other timing I add all timings coming from MySensors library (too much for bootloader size) and then remove one by one until communication errors start to appear.
Based on that I decided to keep the 4us Tpece2cns and the 10us in SPIBytes. The 10us are really based on tests not on documentation.

**Comment by gnalbandian** [comment]
Hi @Akubi. Great work although I haven't test it yet, it looks promising.

Have you commited this changes to the mysensors git, the 4uS delay change?

**Comment by tekka007** [comment]
@gnalbandian yes, they are merged to dev (see above)

**Comment by Akubi** [comment]
@gnalbandian

yes for MySensorsBootloaderRF24 on dev as explainde by tekka007

For mysensors main project the situation is different. CE_HIGH and CNS_LOW are in different functions.
If my estimation is correct the delay due to code execution is more than 4us at 16MHz.
Maby that can be an issue for faster CPU

@tekka007, you are most experienced than me on mysensors. What is your feeling ?

**Comment by tekka007** [comment]
@Akubi That's a valid thought - maybe a logic analyzer can shed some light here. However, I cannot recall RF24 issues on a RPI. 

I guess this delay could possibly be an issue and should be placed before csn_low(), set to 4us:
https://github.com/mysensors/MySensors/blob/development/drivers/RF24/RF24.cpp#L65

**Pull request merged**
